# Site settings
title: Learning The Things
email: "imlearningthethings@gmail.com"
description: Maria Guideng
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://mariaguideng.github.io"
twitter_username: jekyllrb
github_username:  mariaguideng

# Build settings
markdown: kramdown
