# Site settings
title: Maria Guideng
email: "imlearningthethings@gmail.com"
description: Learning the Things
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://mariaguideng.github.io"
twitter_username: jekyllrb
github_username:  mariaguideng

# Build settings
markdown: kramdown
